FROM ruby:2.7.0 AS base

WORKDIR /backend

RUN apt-get update -qq && apt-get install -y postgresql-client

COPY . .

RUN bundle install

FROM base AS dev

WORKDIR /backend

COPY --from=base /backend /backend

EXPOSE 3333

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3333"]