version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["rails", "server", "-b", "0.0.0.0", "-p", "3333"]
    ports:
      - "3333:3333"
    volumes: 
      - "//d/programming/.bashrc:/root/.bashrc"
    depends_on: 
      - db
  db:
    image: postgres:10.11
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: 