FROM ruby:2.7.0

RUN apt-get update -qq && apt-get install -y postgresql-client
WORKDIR /backend
COPY Gemfile /backend/Gemfile
COPY Gemfile.lock /backend/Gemfile.lock
RUN bundle install
COPY . /backend

EXPOSE 3333

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3333"]